source 'https://rubygems.org'

gem 'sinatra'
gem 'hellosign-ruby-sdk'
gem 'rspec'
gem 'sinatra-assetpack', :require => 'sinatra/assetpack'
gem 'sinatra-contrib'
gem 'compass'
gem 'savon', '~> 2.8.0'
gem 'tiny_tds'
gem 'dotenv'
gem 'thin'
